version: 2
references:
  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root



workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test-chrome:
          requires:
            - build
      - test-phantomjs:
          requires:
            - build
  release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test-chrome:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - create-package:
          requires:
            - test-chrome
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - bintray-upload:
          requires:
            - create-package
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/


jobs:
##################################################################
##
##BUILD JOB
##
##################################################################
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8u141-browsers

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m



    steps:
      - checkout

      - restore_cache:
            keys:
              # when lock file changes, use increasingly general patterns to restore cache
              - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
              - maven-repo-v1-{{ .Branch }}-
              - maven-repo-v1-

      - run: mvn install -DskipTests=true -DfailIfNoTests=false

      - save_cache:
            paths:
              - ~/.m2
            key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
#      - run:
#          name: Install Firfox
#          command: |
#            firefox -v | more
#            which firefox
#
#      - run:
#          name: Install gecko driver
#          command: |
#            sudo wget https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-linux64.tar.gz
#            sudo tar -xvzf geckodriver*
#            sudo chmod +x geckodriver
#            sudo mv geckodriver /usr/bin/
#
#      - run:
#          name: Install fluxbox
#          command: sudo apt-get install fluxbox
#
#      - run:
#          name: start xvfb
#          command: |
#            export DISPLAY=:99
#            Xvfb :99 -ac -screen 1 1024x768x24 & fluxbox &
#          background: true
#
#      - run:
#          name: Install phantomJS
#          command: |
#            wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
#            bzip2 -d phantomjs-2.1.1-linux-x86_64.tar.bz2
#            tar -xvf phantomjs-2.1.1-linux-x86_64.tar
#            sudo cp phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin/phantomjs
#            phantomjs -v
#
#      - run: mvn install -DskipTests=true -DfailIfNoTests=false
#
#      - run:
#          name: UI Tests
#          command: mvn test -Dwebdriver.chrome.driver=/usr/bin/chromedriver -Dwebdriver.gecko.driver=/usr/bin/geckodriver
#
#      - save_cache:
#          paths:
#            - ~/.m2
#          key: v1-dependencies-{{ checksum "pom.xml" }}
#
#
#      - run:
#          name: Save test results
#          command: |
#             mkdir -p ~/junit/
#             find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
#          when: always
#
#      - store_test_results:
#          path: ~/junit
#
#      - run:
#          command: |
#            touch ~/repo/junit-tests/target/mvnrelease.out
#            touch ~/repo/junit-tests/target/circleTag.out
#            echo $CIRCLE_TAG > ~/repo/junit-tests/target/circleTag.out
#            export MAVEN_RELEASE_VERSION="$(echo $CIRCLE_TAG | cut -c 2-)"
#            echo $MAVEN_RELEASE_VERSION > ~/repo/junit-tests/target/mvnrelease.out
#
#      - store_artifacts:
#                path: ~/repo/junit-tests/target

##################################################################
##
##TEST-CHROME JOB
##
##################################################################
  test-chrome:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8u141-browsers

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m



    steps:

      - checkout

      - restore_cache:
            keys:
              # when lock file changes, use increasingly general patterns to restore cache
              - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
              - maven-repo-v1-{{ .Branch }}-
              - maven-repo-v1-

      - run:
          name: Install latest Chrome browser
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get install google-chrome-stable
            google-chrome --version


      - run:
          name: Install latest version of ChromeDriver
          command: |
            sudo wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE
            lastVersion=$(cat LATEST_RELEASE)
            sudo wget "https://chromedriver.storage.googleapis.com/$url${lastVersion}/chromedriver_linux64.zip"
            sudo unzip chromedriver_linux64.zip
            sudo rm chromedriver_linux64.zip
            sudo mv chromedriver /usr/bin/
            sudo chmod 777 /usr/bin/chromedriver
            sudo apt-get install libxi6 libgconf-2-4
            sudo apt-get -y install xvfb gtk2-engines-pixbuf
            sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
            sudo apt-get install xvfb
            sudo apt-get -y install imagemagick x11-apps

      - run:
          name: Install fluxbox
          command: sudo apt-get install fluxbox

      - run:
          name: start xvfb
          command: |
            export DISPLAY=:99
            Xvfb :99 -ac -screen 1 1024x768x24 & fluxbox &
          background: true

      - run:
          name: UI Tests
          command: mvn test -Pbrowser -Dwebdriver.chrome.driver=/usr/bin/chromedriver -Dwebdriver.gecko.driver=/usr/bin/geckodriver

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}


      - run:
          name: Save test results
          command: |
             mkdir -p ~/junit/
             find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      - run:
          command: |
            touch ~/repo/junit-tests/target/mvnrelease.out
            touch ~/repo/junit-tests/target/circleTag.out
            echo $CIRCLE_TAG > ~/repo/junit-tests/target/circleTag.out
            export MAVEN_RELEASE_VERSION="$(echo $CIRCLE_TAG | cut -c 2-)"
            echo $MAVEN_RELEASE_VERSION > ~/repo/junit-tests/target/mvnrelease.out

      - store_artifacts:
                path: ~/repo/junit-tests/target

##################################################################
##
##TEST-PHATNOMJS JOB
##
##################################################################
  test-phantomjs:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8u141-browsers

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:

      - checkout

      - restore_cache:
            keys:
              # when lock file changes, use increasingly general patterns to restore cache
              - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
              - maven-repo-v1-{{ .Branch }}-
              - maven-repo-v1-

      - run:
          name: Install phantomJS
          command: |
            wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
            bzip2 -d phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar -xvf phantomjs-2.1.1-linux-x86_64.tar
            sudo cp phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin/phantomjs
            phantomjs -v



      - run:
          name: UI Tests
          command: mvn test -Pbrowser-headless -Dbrowser=phantomjs

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}


      - run:
          name: Save test results
          command: |
             mkdir -p ~/junit/
             find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit

      - run:
          command: |
            touch ~/repo/junit-tests/target/mvnrelease.out
            touch ~/repo/junit-tests/target/circleTag.out
            echo $CIRCLE_TAG > ~/repo/junit-tests/target/circleTag.out
            export MAVEN_RELEASE_VERSION="$(echo $CIRCLE_TAG | cut -c 2-)"
            echo $MAVEN_RELEASE_VERSION > ~/repo/junit-tests/target/mvnrelease.out

      - store_artifacts:
                path: ~/repo/junit-tests/target


##################################################################
##
##CREATE PACKAGE JOB
##
##################################################################
  create-package:
    docker:
          # specify the version you desire here
          - image: circleci/openjdk:8u141-browsers

    working_directory: ~/repo

    steps:
#      - restore_cache:
#            keys:
#              - source-v1-{{ .Branch }}-{{ .Revision }}
#              - source-v1-{{ .Branch }}-
#              - source-v1-

      - checkout

      - restore_cache:
            keys:
              # when lock file changes, use increasingly general patterns to restore cache
              - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
              - maven-repo-v1-{{ .Branch }}-
              - maven-repo-v1-


      - run:
          name: Updating Maui version as per tag
          command: |
            export MAVEN_RELEASE_VERSION="$(echo $CIRCLE_TAG | cut -c 2-)"
            mvn versions:set -DnewVersion=$MAVEN_RELEASE_VERSION -f maui/pom.xml
            mvn versions:commit

      - run:
          name: Building packages
          command: |
            export MAVEN_RELEASE_VERSION="$(echo $CIRCLE_TAG | cut -c 2-)"
            cd maui
            mvn clean package -DskipTests=true
            mkdir ~/repo/maui/releasePackage
            mkdir -p /tmp/workspace/release/jars
            mv ~/repo/maui/target/*.jar /tmp/workspace/release/jars/
            export POM_NAME_1='/tmp/workspace/release/jars/maui-'
            export POM_NAME_2='.pom'
            export POM_FULL_NAME="$POM_NAME_1$MAVEN_RELEASE_VERSION$POM_NAME_2"
            cp ~/repo/maui/pom.xml $POM_FULL_NAME

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - release/jars/

      - run:
          name: Setting new development version as per tag
          command: |
            export MAVEN_RELEASE_VERSION="$(echo $CIRCLE_TAG | cut -c 2-)"
            export MAVEN_SNAPSHOT='-SNAPSHOT'
            export DEVELOPMENT_VERSION="$MAVEN_RELEASE_VERSION$MAVEN_SNAPSHOT"
            touch ~/repo/maui/target/devTag.out
                        echo $DEVELOPMENT_VERSION > ~/repo/maui/target/devTag.out
            mvn versions:set -DnewVersion=$DEVELOPMENT_VERSION -f maui/pom.xml
            mvn versions:commit

      - store_artifacts:
          path: ~/repo/maui/target

##################################################################
##
##BINTRAY UPLOAD JOB
##
##################################################################
  bintray-upload:
    docker:
            # specify the version you desire here
      - image: circleci/openjdk:8u141-browsers

    working_directory: ~/repo

    steps:
      - *attach_workspace

      - run:
          name: install Bintray CLI
          command: |
            cd /tmp
            sudo curl -fL https://getcli.jfrog.io | sh

      - run:
          name: upload artifacts to bintray
          command: |
            export MAVEN_RELEASE_VERSION="$(echo $CIRCLE_TAG | cut -c 2-)"
            export MAUI_URL='testmonkeys/maven/maui/'
            export MAUI_PACKAGE='org/testmonkeys/maui/'
            export VCS_URL='https://github.com/TestMonkeys/maui.git'
            export BINTRAY_URL="$MAUI_URL$MAVEN_RELEASE_VERSION"
            export SEPARATOR='/'
            export PATH="$MAUI_PACKAGE$MAVEN_RELEASE_VERSION$SEPARATOR"
            /tmp/jfrog bt config --user=$BINTRAY_USER --key=$BINTRAY_API_KEY --licenses="Apache-2.0"
            /tmp/jfrog bt u "/tmp/workspace/release/jars/*" $BINTRAY_URL $PATH
            /tmp/jfrog bt gsv $BINTRAY_URL --passphrase=$BINTRAY_GPG_PWD
            /tmp/jfrog bt vp $BINTRAY_URL
      - run:
          name: Sync to Maven Central
          command: |
            sudo apt-get update
            sudo apt-get install gettext
            export MAVEN_RELEASE_VERSION="$(echo $CIRCLE_TAG | cut -c 2-)"
            echo '{"username": "$SONATYPE_USER","password": "$SONATYPE_PASSWORD","close": "1"}' > req.template
            envsubst < req.template > request
            sudo curl -u $BINTRAY_USER:$BINTRAY_API_KEY --header "Content-Type: application/json" --data '@./request' --request POST https://api.bintray.com/maven_central_sync/testmonkeys/maven/maui/versions/$MAVEN_RELEASE_VERSION
            rm request
